name: test-on-push
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make test

  e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make test-e2e

  check-api-reference:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: make check-api-reference

  check-docs-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: make build-docs
